MobileBarkodOkuma/Controllers/UrunAramaController.cs
using Lizay.dll.CaniasWS;
using MobileBarkodOkuma.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MobileBarkodOkuma.Controllers
{
    public class UrunAramaController : Controller
    {
        // GET: UrunArama
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ReadBarcode(string barcodeData)
        {
            if (string.IsNullOrEmpty(barcodeData)) return View("Index");
            if (!ModelState.IsValid) return View("Index");

            var sessionId = "";
            List<BarcodeViewModel> barcode;
            var caniasWebService = new iasWebServiceImplService();

            try
            {
                var arg = "IYILMAZ," + barcodeData;

                sessionId = caniasWebService.login("00", "T", "NEW", "CANIAS", "192.168.1.50:27499/S2", "WSLIZAY", "Ws-123lizay");
                var resp = caniasWebService.callIASService(sessionId, "RetailBatchCheck", arg, "STRING", true);

                var json = resp.ToString().Replace("[]", "''");
                barcode = JsonConvert.DeserializeObject<List<BarcodeViewModel>>(json);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);

                if (!string.IsNullOrEmpty(sessionId))
                    caniasWebService.logout(sessionId);

                return View("Index");
            }
            finally
            {
                if (!string.IsNullOrEmpty(sessionId))
                    caniasWebService.logout(sessionId);
            }

            if (barcode == null) return View("Index");

            TempData["BarcodeList"] = barcode;


            //return RedirectToAction("Index", "UrunArama1");
            return Json(Url.Action("Index", "UrunArama1"));

        }

        //[HttpPost]
        //public JsonResult AjaxMethod(PersonModel person)
        //{
        //    int personId = person.PersonId;
        //    string name = person.Name;
        //    string gender = person.Gender;
        //    string city = person.City;
        //    return Json(person);
        //}
    }
}

MobileBarkodOkuma/Views/UrunArama/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ürün Ekranı</title>
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/carousel.css" rel="stylesheet" />
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link href="~/assets/css/font-awasome.css" rel="stylesheet" />
    <link href="~/assets/css/fonts.css" rel="stylesheet" />
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>

        .modal {
            position: fixed;
            z-index: 999;
            height: 100%;
            width: 100%;
            top: 0;
            background-color: Black;
            filter: alpha(opacity=60);
            opacity: 0.6;
            -moz-opacity: 0.8;
            display: none;
        }

        .center {
            z-index: 1000;
            margin: 50px auto;
            padding: 10px;
            width: 130px;
            background-color: transparent;
            border-radius: 10px;
            filter: alpha(opacity=100);
            opacity: 1;
            -moz-opacity: 1;
        }



        .responsive {
            padding-top: 80px;
            width: 100%;
            height: auto;
        }
    </style>

</head>
<body>
    @*@using (Html.BeginForm("ReadBarcode", "UrunArama", FormMethod.Post))
        {*@

    @using (Ajax.BeginForm("ReadBarcode", "UrunArama",
        new AjaxOptions
        {
            OnSuccess = "OnSuccess",
            OnFailure = "OnFailure",
            LoadingElementId = "progress"
        }))
    {
        <div class="container" style="margin-bottom: 30px;">
            <div class="row">
                <div class="form-signin">
                    <h2 class="form-signin-heading" style="margin-top: 150px; padding-bottom: 50px;">Ürün Arama Ekranı</h2>
                    <input type="text" name="barcodeData" id="txtBarkod" class="form-control" placeholder="Ürün Kodu Giriniz" required="" autofocus="">
                    <button class="btn btn-lg btn-primary btn-block" style="margin-top: 20px;" type="submit">Ürün Ara</button>


                </div>
            </div>
        </div>
    }

    <div id="progress" class="modal">
        <div class="center">
            <img src="~/assets/images/loaderNews.gif" alt="" class="center-block responsive" />
        </div>
    </div>

    <script src="~/assets/js/hover.js"></script>
    <script src="~/assets/js/holder.min.js"></script>
    <script src="~/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/jquery-1.11.0.min.js"></script>
    <script src="~/assets/js/jquery.unobtrusive-ajax.min.js"></script>

    <script type="text/javascript">
        function OnSuccess(data) {
            window.location.href = data;
        }
        function OnFailure(response) {
            //alert("Error occured.");
        }
    </script>

    <script>
        window.onscroll = function () { myFunction() };

        var navbar = document.getElementById("sabitmenu");
        var sticky = navbar.offsetTop;

        function myFunction() {
            if (window.pageYOffset >= sticky) {
                navbar.classList.add("sticky")
            } else {
                navbar.classList.remove("sticky");
            }
        }
    </script>

    <script>
        $(document).ready(function () {
            // -----------------------------------------------------------------------
            $.each($('#navbar').find('li'),
                function () {
                    $(this).toggleClass('active',
                        window.location.pathname.indexOf($(this).find('a').attr('href')) > -1);
                });
            // -----------------------------------------------------------------------
        });
    </script>
    <script src="~/assets/js/up.js"></script>
</body>
</html>